/* automatically generated by rust-bindgen */

pub type uintptr_t = ::std::os::raw::c_ulonglong;
pub type va_list = *mut ::std::os::raw::c_char;
pub type size_t = ::std::os::raw::c_ulonglong;
pub type ptrdiff_t = ::std::os::raw::c_longlong;
pub type intptr_t = ::std::os::raw::c_longlong;
pub type wchar_t = ::std::os::raw::c_ushort;
pub type int8_t = ::std::os::raw::c_char;
pub type int16_t = ::std::os::raw::c_short;
pub type int32_t = ::std::os::raw::c_int;
pub type int64_t = ::std::os::raw::c_longlong;
pub type uint8_t = ::std::os::raw::c_uchar;
pub type uint16_t = ::std::os::raw::c_ushort;
pub type uint32_t = ::std::os::raw::c_uint;
pub type uint64_t = ::std::os::raw::c_ulonglong;
pub type int_least8_t = ::std::os::raw::c_char;
pub type int_least16_t = ::std::os::raw::c_short;
pub type int_least32_t = ::std::os::raw::c_int;
pub type int_least64_t = ::std::os::raw::c_longlong;
pub type uint_least8_t = ::std::os::raw::c_uchar;
pub type uint_least16_t = ::std::os::raw::c_ushort;
pub type uint_least32_t = ::std::os::raw::c_uint;
pub type uint_least64_t = ::std::os::raw::c_ulonglong;
pub type int_fast8_t = ::std::os::raw::c_char;
pub type int_fast16_t = ::std::os::raw::c_int;
pub type int_fast32_t = ::std::os::raw::c_int;
pub type int_fast64_t = ::std::os::raw::c_longlong;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_uint;
pub type uint_fast32_t = ::std::os::raw::c_uint;
pub type uint_fast64_t = ::std::os::raw::c_ulonglong;
pub type intmax_t = ::std::os::raw::c_longlong;
pub type uintmax_t = ::std::os::raw::c_ulonglong;
pub type ovrResult = int32_t;
#[derive(Clone, Copy)]
#[repr(i32)]
pub enum Enum_ovrSuccessType_ {
    ovrSuccess = 0,
    ovrSuccess_NotVisible = 1000,
    ovrSuccess_HMDFirmwareMismatch = 4100,
    ovrSuccess_TrackerFirmwareMismatch = 4101,
    ovrSuccess_ControllerFirmwareMismatch = 4104,
}
pub type ovrSuccessType = Enum_ovrSuccessType_;
#[derive(Clone, Copy)]
#[repr(i32)]
pub enum Enum_ovrErrorType_ {
    ovrError_MemoryAllocationFailure = -1000,
    ovrError_SocketCreationFailure = -1001,
    ovrError_InvalidSession = -1002,
    ovrError_Timeout = -1003,
    ovrError_NotInitialized = -1004,
    ovrError_InvalidParameter = -1005,
    ovrError_ServiceError = -1006,
    ovrError_NoHmd = -1007,
    ovrError_AudioReservedBegin = -2000,
    ovrError_AudioDeviceNotFound = -2001,
    ovrError_AudioComError = -2002,
    ovrError_AudioReservedEnd = -2999,
    ovrError_Initialize = -3000,
    ovrError_LibLoad = -3001,
    ovrError_LibVersion = -3002,
    ovrError_ServiceConnection = -3003,
    ovrError_ServiceVersion = -3004,
    ovrError_IncompatibleOS = -3005,
    ovrError_DisplayInit = -3006,
    ovrError_ServerStart = -3007,
    ovrError_Reinitialization = -3008,
    ovrError_MismatchedAdapters = -3009,
    ovrError_LeakingResources = -3010,
    ovrError_ClientVersion = -3011,
    ovrError_OutOfDateOS = -3012,
    ovrError_OutOfDateGfxDriver = -3013,
    ovrError_IncompatibleGPU = -3014,
    ovrError_NoValidVRDisplaySystem = -3015,
    ovrError_InvalidBundleAdjustment = -4000,
    ovrError_USBBandwidth = -4001,
    ovrError_USBEnumeratedSpeed = -4002,
    ovrError_ImageSensorCommError = -4003,
    ovrError_GeneralTrackerFailure = -4004,
    ovrError_ExcessiveFrameTruncation = -4005,
    ovrError_ExcessiveFrameSkipping = -4006,
    ovrError_SyncDisconnected = -4007,
    ovrError_TrackerMemoryReadFailure = -4008,
    ovrError_TrackerMemoryWriteFailure = -4009,
    ovrError_TrackerFrameTimeout = -4010,
    ovrError_TrackerTruncatedFrame = -4011,
    ovrError_HMDFirmwareMismatch = -4100,
    ovrError_TrackerFirmwareMismatch = -4101,
    ovrError_BootloaderDeviceDetected = -4102,
    ovrError_TrackerCalibrationError = -4103,
    ovrError_ControllerFirmwareMismatch = -4104,
    ovrError_Incomplete = -5000,
    ovrError_Abandoned = -5001,
    ovrError_DisplayLost = -6000,
    ovrError_RuntimeException = -7000,
}
pub type ovrErrorType = Enum_ovrErrorType_;
pub type ovrBool = ::std::os::raw::c_char;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrVector2i_ {
    pub x: ::std::os::raw::c_int,
    pub y: ::std::os::raw::c_int,
}
impl ::std::clone::Clone for Struct_ovrVector2i_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrVector2i_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrVector2i = Struct_ovrVector2i_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrSizei_ {
    pub w: ::std::os::raw::c_int,
    pub h: ::std::os::raw::c_int,
}
impl ::std::clone::Clone for Struct_ovrSizei_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrSizei_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrSizei = Struct_ovrSizei_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrRecti_ {
    pub Pos: ovrVector2i,
    pub Size: ovrSizei,
}
impl ::std::clone::Clone for Struct_ovrRecti_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrRecti_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrRecti = Struct_ovrRecti_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrQuatf_ {
    pub x: ::std::os::raw::c_float,
    pub y: ::std::os::raw::c_float,
    pub z: ::std::os::raw::c_float,
    pub w: ::std::os::raw::c_float,
}
impl ::std::clone::Clone for Struct_ovrQuatf_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrQuatf_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrQuatf = Struct_ovrQuatf_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrVector2f_ {
    pub x: ::std::os::raw::c_float,
    pub y: ::std::os::raw::c_float,
}
impl ::std::clone::Clone for Struct_ovrVector2f_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrVector2f_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrVector2f = Struct_ovrVector2f_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrVector3f_ {
    pub x: ::std::os::raw::c_float,
    pub y: ::std::os::raw::c_float,
    pub z: ::std::os::raw::c_float,
}
impl ::std::clone::Clone for Struct_ovrVector3f_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrVector3f_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrVector3f = Struct_ovrVector3f_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrMatrix4f_ {
    pub M: [[::std::os::raw::c_float; 4usize]; 4usize],
}
impl ::std::clone::Clone for Struct_ovrMatrix4f_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrMatrix4f_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrMatrix4f = Struct_ovrMatrix4f_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrPosef_ {
    pub Orientation: ovrQuatf,
    pub Position: ovrVector3f,
}
impl ::std::clone::Clone for Struct_ovrPosef_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrPosef_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrPosef = Struct_ovrPosef_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrPoseStatef_ {
    pub ThePose: ovrPosef,
    pub AngularVelocity: ovrVector3f,
    pub LinearVelocity: ovrVector3f,
    pub AngularAcceleration: ovrVector3f,
    pub LinearAcceleration: ovrVector3f,
    pub pad0: [::std::os::raw::c_char; 4usize],
    pub TimeInSeconds: ::std::os::raw::c_double,
}
impl ::std::clone::Clone for Struct_ovrPoseStatef_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrPoseStatef_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrPoseStatef = Struct_ovrPoseStatef_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrFovPort_ {
    pub UpTan: ::std::os::raw::c_float,
    pub DownTan: ::std::os::raw::c_float,
    pub LeftTan: ::std::os::raw::c_float,
    pub RightTan: ::std::os::raw::c_float,
}
impl ::std::clone::Clone for Struct_ovrFovPort_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrFovPort_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrFovPort = Struct_ovrFovPort_;
#[derive(Clone, Copy)]
#[repr(i32)]
pub enum Enum_ovrHmdType_ {
    ovrHmd_None = 0,
    ovrHmd_DK1 = 3,
    ovrHmd_DKHD = 4,
    ovrHmd_DK2 = 6,
    ovrHmd_CB = 8,
    ovrHmd_Other = 9,
    ovrHmd_E3_2015 = 10,
    ovrHmd_ES06 = 11,
    ovrHmd_ES09 = 12,
    ovrHmd_EnumSize = 2147483647,
}
pub type ovrHmdType = Enum_ovrHmdType_;
pub const ovrHmdCap_Service_Mask: Enum_ovrHmdCaps_ =
    Enum_ovrHmdCaps_::ovrHmdCap_Writable_Mask;
#[derive(Clone, Copy)]
#[repr(i32)]
pub enum Enum_ovrHmdCaps_ {
    ovrHmdCap_DebugDevice = 16,
    ovrHmdCap_Writable_Mask = 0,
    ovrHmdCap_EnumSize = 2147483647,
}
pub type ovrHmdCaps = Enum_ovrHmdCaps_;
#[derive(Clone, Copy)]
#[repr(i32)]
pub enum Enum_ovrTrackingCaps_ {
    ovrTrackingCap_Orientation = 16,
    ovrTrackingCap_MagYawCorrection = 32,
    ovrTrackingCap_Position = 64,
    ovrTrackingCap_EnumSize = 2147483647,
}
pub type ovrTrackingCaps = Enum_ovrTrackingCaps_;
#[derive(Clone, Copy)]
#[repr(i32)]
pub enum Enum_ovrEyeType_ {
    ovrEye_Left = 0,
    ovrEye_Right = 1,
    ovrEye_Count = 2,
    ovrEye_EnumSize = 2147483647,
}
pub type ovrEyeType = Enum_ovrEyeType_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrGraphicsLuid_ {
    pub Reserved: [::std::os::raw::c_char; 8usize],
}
impl ::std::clone::Clone for Struct_ovrGraphicsLuid_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrGraphicsLuid_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrGraphicsLuid = Struct_ovrGraphicsLuid_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrHmdDesc_ {
    pub Type: ovrHmdType,
    pub pad0: [::std::os::raw::c_char; 4usize],
    pub ProductName: [::std::os::raw::c_char; 64usize],
    pub Manufacturer: [::std::os::raw::c_char; 64usize],
    pub VendorId: ::std::os::raw::c_short,
    pub ProductId: ::std::os::raw::c_short,
    pub SerialNumber: [::std::os::raw::c_char; 24usize],
    pub FirmwareMajor: ::std::os::raw::c_short,
    pub FirmwareMinor: ::std::os::raw::c_short,
    pub CameraFrustumHFovInRadians: ::std::os::raw::c_float,
    pub CameraFrustumVFovInRadians: ::std::os::raw::c_float,
    pub CameraFrustumNearZInMeters: ::std::os::raw::c_float,
    pub CameraFrustumFarZInMeters: ::std::os::raw::c_float,
    pub AvailableHmdCaps: ::std::os::raw::c_uint,
    pub DefaultHmdCaps: ::std::os::raw::c_uint,
    pub AvailableTrackingCaps: ::std::os::raw::c_uint,
    pub DefaultTrackingCaps: ::std::os::raw::c_uint,
    pub DefaultEyeFov: [ovrFovPort; 2usize],
    pub MaxEyeFov: [ovrFovPort; 2usize],
    pub Resolution: ovrSizei,
    pub DisplayRefreshRate: ::std::os::raw::c_float,
    pub pad1: [::std::os::raw::c_char; 4usize],
}
impl ::std::clone::Clone for Struct_ovrHmdDesc_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrHmdDesc_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrHmdDesc = Struct_ovrHmdDesc_;
pub enum Struct_ovrHmdStruct { }
pub type ovrSession = *mut Struct_ovrHmdStruct;
pub type ovrHmd = *mut Struct_ovrHmdStruct;
#[derive(Clone, Copy)]
#[repr(i32)]
pub enum Enum_ovrStatusBits_ {
    ovrStatus_OrientationTracked = 1,
    ovrStatus_PositionTracked = 2,
    ovrStatus_CameraPoseTracked = 4,
    ovrStatus_PositionConnected = 32,
    ovrStatus_HmdConnected = 128,
    ovrStatus_EnumSize = 2147483647,
}
pub type ovrStatusBits = Enum_ovrStatusBits_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrSensorData_ {
    pub Accelerometer: ovrVector3f,
    pub Gyro: ovrVector3f,
    pub Magnetometer: ovrVector3f,
    pub Temperature: ::std::os::raw::c_float,
    pub TimeInSeconds: ::std::os::raw::c_float,
}
impl ::std::clone::Clone for Struct_ovrSensorData_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrSensorData_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrSensorData = Struct_ovrSensorData_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrTrackingState_ {
    pub HeadPose: ovrPoseStatef,
    pub CameraPose: ovrPosef,
    pub LeveledCameraPose: ovrPosef,
    pub HandPoses: [ovrPoseStatef; 2usize],
    pub RawSensorData: ovrSensorData,
    pub StatusFlags: ::std::os::raw::c_uint,
    pub HandStatusFlags: [::std::os::raw::c_uint; 2usize],
    pub LastCameraFrameCounter: uint32_t,
    pub pad0: [::std::os::raw::c_char; 4usize],
}
impl ::std::clone::Clone for Struct_ovrTrackingState_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrTrackingState_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrTrackingState = Struct_ovrTrackingState_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrEyeRenderDesc_ {
    pub Eye: ovrEyeType,
    pub Fov: ovrFovPort,
    pub DistortedViewport: ovrRecti,
    pub PixelsPerTanAngleAtCenter: ovrVector2f,
    pub HmdToEyeViewOffset: ovrVector3f,
}
impl ::std::clone::Clone for Struct_ovrEyeRenderDesc_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrEyeRenderDesc_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrEyeRenderDesc = Struct_ovrEyeRenderDesc_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrTimewarpProjectionDesc_ {
    pub Projection22: ::std::os::raw::c_float,
    pub Projection23: ::std::os::raw::c_float,
    pub Projection32: ::std::os::raw::c_float,
}
impl ::std::clone::Clone for Struct_ovrTimewarpProjectionDesc_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrTimewarpProjectionDesc_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrTimewarpProjectionDesc = Struct_ovrTimewarpProjectionDesc_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrViewScaleDesc_ {
    pub HmdToEyeViewOffset: [ovrVector3f; 2usize],
    pub HmdSpaceToWorldScaleInMeters: ::std::os::raw::c_float,
}
impl ::std::clone::Clone for Struct_ovrViewScaleDesc_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrViewScaleDesc_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrViewScaleDesc = Struct_ovrViewScaleDesc_;
#[derive(Clone, Copy)]
#[repr(i32)]
pub enum Enum_ovrRenderAPIType_ {
    ovrRenderAPI_None = 0,
    ovrRenderAPI_OpenGL = 1,
    ovrRenderAPI_Android_GLES = 2,
    ovrRenderAPI_D3D11 = 5,
    ovrRenderAPI_Count = 4,
    ovrRenderAPI_EnumSize = 2147483647,
}
pub type ovrRenderAPIType = Enum_ovrRenderAPIType_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrTextureHeader_ {
    pub API: ovrRenderAPIType,
    pub TextureSize: ovrSizei,
}
impl ::std::clone::Clone for Struct_ovrTextureHeader_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrTextureHeader_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrTextureHeader = Struct_ovrTextureHeader_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrTexture_ {
    pub Header: ovrTextureHeader,
    pub pad0: [::std::os::raw::c_char; 4usize],
    pub PlatformData: [uintptr_t; 8usize],
}
impl ::std::clone::Clone for Struct_ovrTexture_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrTexture_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrTexture = Struct_ovrTexture_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrSwapTextureSet_ {
    pub Textures: *mut ovrTexture,
    pub TextureCount: ::std::os::raw::c_int,
    pub CurrentIndex: ::std::os::raw::c_int,
}
impl ::std::clone::Clone for Struct_ovrSwapTextureSet_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrSwapTextureSet_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrSwapTextureSet = Struct_ovrSwapTextureSet_;
#[derive(Clone, Copy)]
#[repr(i32)]
pub enum Enum_ovrButton_ {
    ovrButton_A = 1,
    ovrButton_B = 2,
    ovrButton_RThumb = 4,
    ovrButton_RShoulder = 8,
    ovrButton_X = 256,
    ovrButton_Y = 512,
    ovrButton_LThumb = 1024,
    ovrButton_LShoulder = 2048,
    ovrButton_Up = 65536,
    ovrButton_Down = 131072,
    ovrButton_Left = 262144,
    ovrButton_Right = 524288,
    ovrButton_Enter = 1048576,
    ovrButton_Back = 2097152,
    ovrButton_Private = 29360128,
    ovrButton_EnumSize = 2147483647,
}
pub type ovrButton = Enum_ovrButton_;
#[derive(Clone, Copy)]
#[repr(i32)]
pub enum Enum_ovrTouch_ {
    ovrTouch_A = 1,
    ovrTouch_B = 2,
    ovrTouch_RThumb = 4,
    ovrTouch_RIndexTrigger = 16,
    ovrTouch_X = 256,
    ovrTouch_Y = 512,
    ovrTouch_LThumb = 1024,
    ovrTouch_LIndexTrigger = 4096,
    ovrTouch_RIndexPointing = 32,
    ovrTouch_RThumbUp = 64,
    ovrTouch_LIndexPointing = 8192,
    ovrTouch_LThumbUp = 16384,
    ovrTouch_EnumSize = 2147483647,
}
pub type ovrTouch = Enum_ovrTouch_;
#[derive(Clone, Copy)]
#[repr(i32)]
pub enum Enum_ovrControllerType_ {
    ovrControllerType_None = 0,
    ovrControllerType_LTouch = 1,
    ovrControllerType_RTouch = 2,
    ovrControllerType_Touch = 3,
    ovrControllerType_XBox = 16,
    ovrControllerType_All = 255,
    ovrControllerType_EnumSize = 2147483647,
}
pub type ovrControllerType = Enum_ovrControllerType_;
#[derive(Clone, Copy)]
#[repr(i32)]
pub enum Enum_ovrHandType_ {
    ovrHand_Left = 0,
    ovrHand_Right = 1,
    ovrHand_EnumSize = 2147483647,
}
pub type ovrHandType = Enum_ovrHandType_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrInputState_ {
    pub TimeInSeconds: ::std::os::raw::c_double,
    pub ConnectedControllerTypes: ::std::os::raw::c_uint,
    pub Buttons: ::std::os::raw::c_uint,
    pub Touches: ::std::os::raw::c_uint,
    pub IndexTrigger: [::std::os::raw::c_float; 2usize],
    pub HandTrigger: [::std::os::raw::c_float; 2usize],
    pub Thumbstick: [ovrVector2f; 2usize],
}
impl ::std::clone::Clone for Struct_ovrInputState_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrInputState_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrInputState = Struct_ovrInputState_;
#[derive(Clone, Copy)]
#[repr(i32)]
pub enum Enum_ovrInitFlags_ {
    ovrInit_Debug = 1,
    ovrInit_RequestVersion = 4,
    ovrinit_WritableBits = 16777215,
    ovrInit_EnumSize = 2147483647,
}
pub type ovrInitFlags = Enum_ovrInitFlags_;
#[derive(Clone, Copy)]
#[repr(i32)]
pub enum Enum_ovrLogLevel_ {
    ovrLogLevel_Debug = 0,
    ovrLogLevel_Info = 1,
    ovrLogLevel_Error = 2,
    ovrLogLevel_EnumSize = 2147483647,
}
pub type ovrLogLevel = Enum_ovrLogLevel_;
pub type ovrLogCallback =
    ::std::option::Option<unsafe extern "C" fn(userData: uintptr_t,
                                               level: ::std::os::raw::c_int,
                                               message:
                                                   *const ::std::os::raw::c_char)>;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrInitParams_ {
    pub Flags: uint32_t,
    pub RequestedMinorVersion: uint32_t,
    pub LogCallback: ovrLogCallback,
    pub UserData: uintptr_t,
    pub ConnectionTimeoutMS: uint32_t,
    pub pad0: [::std::os::raw::c_char; 4usize],
}
impl ::std::clone::Clone for Struct_ovrInitParams_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrInitParams_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrInitParams = Struct_ovrInitParams_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrErrorInfo_ {
    pub Result: ovrResult,
    pub ErrorString: [::std::os::raw::c_char; 512usize],
}
impl ::std::clone::Clone for Struct_ovrErrorInfo_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrErrorInfo_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrErrorInfo = Struct_ovrErrorInfo_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrSessionStatus_ {
    pub HasVrFocus: ovrBool,
    pub HmdPresent: ovrBool,
}
impl ::std::clone::Clone for Struct_ovrSessionStatus_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrSessionStatus_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrSessionStatus = Struct_ovrSessionStatus_;
#[derive(Clone, Copy)]
#[repr(i32)]
pub enum Enum_Unnamed1 { ovrMaxLayerCount = 32, }
#[derive(Clone, Copy)]
#[repr(i32)]
pub enum Enum_ovrLayerType_ {
    ovrLayerType_Disabled = 0,
    ovrLayerType_EyeFov = 1,
    ovrLayerType_EyeFovDepth = 2,
    ovrLayerType_Quad = 3,
    ovrLayerType_EyeMatrix = 5,
    ovrLayerType_Direct = 6,
    ovrLayerType_EnumSize = 2147483647,
}
pub type ovrLayerType = Enum_ovrLayerType_;
#[derive(Clone, Copy)]
#[repr(i32)]
pub enum Enum_ovrLayerFlags_ {
    ovrLayerFlag_HighQuality = 1,
    ovrLayerFlag_TextureOriginAtBottomLeft = 2,
    ovrLayerFlag_HeadLocked = 4,
}
pub type ovrLayerFlags = Enum_ovrLayerFlags_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrLayerHeader_ {
    pub Type: ovrLayerType,
    pub Flags: ::std::os::raw::c_uint,
}
impl ::std::clone::Clone for Struct_ovrLayerHeader_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrLayerHeader_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrLayerHeader = Struct_ovrLayerHeader_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrLayerEyeFov_ {
    pub Header: ovrLayerHeader,
    pub ColorTexture: [*mut ovrSwapTextureSet; 2usize],
    pub Viewport: [ovrRecti; 2usize],
    pub Fov: [ovrFovPort; 2usize],
    pub RenderPose: [ovrPosef; 2usize],
    pub SensorSampleTime: ::std::os::raw::c_double,
}
impl ::std::clone::Clone for Struct_ovrLayerEyeFov_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrLayerEyeFov_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrLayerEyeFov = Struct_ovrLayerEyeFov_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrLayerEyeFovDepth_ {
    pub Header: ovrLayerHeader,
    pub ColorTexture: [*mut ovrSwapTextureSet; 2usize],
    pub Viewport: [ovrRecti; 2usize],
    pub Fov: [ovrFovPort; 2usize],
    pub RenderPose: [ovrPosef; 2usize],
    pub SensorSampleTime: ::std::os::raw::c_double,
    pub DepthTexture: [*mut ovrSwapTextureSet; 2usize],
    pub ProjectionDesc: ovrTimewarpProjectionDesc,
}
impl ::std::clone::Clone for Struct_ovrLayerEyeFovDepth_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrLayerEyeFovDepth_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrLayerEyeFovDepth = Struct_ovrLayerEyeFovDepth_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrLayerEyeMatrix_ {
    pub Header: ovrLayerHeader,
    pub ColorTexture: [*mut ovrSwapTextureSet; 2usize],
    pub Viewport: [ovrRecti; 2usize],
    pub RenderPose: [ovrPosef; 2usize],
    pub Matrix: [ovrMatrix4f; 2usize],
    pub SensorSampleTime: ::std::os::raw::c_double,
}
impl ::std::clone::Clone for Struct_ovrLayerEyeMatrix_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrLayerEyeMatrix_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrLayerEyeMatrix = Struct_ovrLayerEyeMatrix_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrLayerQuad_ {
    pub Header: ovrLayerHeader,
    pub ColorTexture: *mut ovrSwapTextureSet,
    pub Viewport: ovrRecti,
    pub QuadPoseCenter: ovrPosef,
    pub QuadSize: ovrVector2f,
}
impl ::std::clone::Clone for Struct_ovrLayerQuad_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrLayerQuad_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrLayerQuad = Struct_ovrLayerQuad_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrLayerDirect_ {
    pub Header: ovrLayerHeader,
    pub ColorTexture: [*mut ovrSwapTextureSet; 2usize],
    pub Viewport: [ovrRecti; 2usize],
}
impl ::std::clone::Clone for Struct_ovrLayerDirect_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrLayerDirect_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrLayerDirect = Struct_ovrLayerDirect_;
#[repr(C)]
#[derive(Copy)]
pub struct Union_ovrLayer_Union_ {
    pub _bindgen_data_: [u64; 23usize],
}
impl Union_ovrLayer_Union_ {
    pub unsafe fn Header(&mut self) -> *mut ovrLayerHeader {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn EyeFov(&mut self) -> *mut ovrLayerEyeFov {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn EyeFovDepth(&mut self) -> *mut ovrLayerEyeFovDepth {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn Quad(&mut self) -> *mut ovrLayerQuad {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn Direct(&mut self) -> *mut ovrLayerDirect {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
}
impl ::std::clone::Clone for Union_ovrLayer_Union_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Union_ovrLayer_Union_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrLayer_Union = Union_ovrLayer_Union_;
#[derive(Clone, Copy)]
#[repr(i32)]
pub enum Enum_ovrPerfHudMode_ {
    ovrPerfHud_Off = 0,
    ovrPerfHud_LatencyTiming = 1,
    ovrPerfHud_RenderTiming = 2,
    ovrPerfHud_PerfHeadroom = 3,
    ovrPerfHud_VersionInfo = 4,
    ovrPerfHud_Count = 5,
    ovrPerfHud_EnumSize = 2147483647,
}
pub type ovrPerfHudMode = Enum_ovrPerfHudMode_;
#[derive(Clone, Copy)]
#[repr(i32)]
pub enum Enum_ovrLayerHudMode_ {
    ovrLayerHud_Off = 0,
    ovrLayerHud_Info = 1,
    ovrLayerHud_EnumSize = 2147483647,
}
pub type ovrLayerHudMode = Enum_ovrLayerHudMode_;
#[derive(Clone, Copy)]
#[repr(i32)]
pub enum Enum_ovrDebugHudStereoMode_ {
    ovrDebugHudStereo_Off = 0,
    ovrDebugHudStereo_Quad = 1,
    ovrDebugHudStereo_QuadWithCrosshair = 2,
    ovrDebugHudStereo_CrosshairAtInfinity = 3,
    ovrDebugHudStereo_Count = 4,
    ovrDebugHudStereo_EnumSize = 2147483647,
}
pub type ovrDebugHudStereoMode = Enum_ovrDebugHudStereoMode_;
pub type compileTimeAssert0 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert1 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert2 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert3 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert4 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert5 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert6 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert7 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert8 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert9 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert10 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert11 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert12 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert13 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert14 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert15 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert16 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert17 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert18 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert19 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert20 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert21 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert22 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert23 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert24 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert25 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert26 = [::std::os::raw::c_char; 1usize];
pub type compileTimeAssert27 = [::std::os::raw::c_char; 1usize];
#[derive(Clone, Copy)]
#[repr(i32)]
pub enum Enum_ovrProjectionModifier_ {
    ovrProjection_None = 0,
    ovrProjection_RightHanded = 1,
    ovrProjection_FarLessThanNear = 2,
    ovrProjection_FarClipAtInfinity = 4,
    ovrProjection_ClipRangeOpenGL = 8,
}
pub type ovrProjectionModifier = Enum_ovrProjectionModifier_;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ovrDetectResult_ {
    pub IsOculusServiceRunning: ovrBool,
    pub IsOculusHMDConnected: ovrBool,
    pub pad0: [::std::os::raw::c_char; 6usize],
}
impl ::std::clone::Clone for Struct_ovrDetectResult_ {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ovrDetectResult_ {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ovrDetectResult = Struct_ovrDetectResult_;
pub type compileTimeAssert28 = [::std::os::raw::c_char; 1usize];
extern "C" {
    pub static mut __security_cookie: uintptr_t;
}
extern "C" {
    pub fn __va_start(arg1: *mut va_list, ...);
    pub fn __security_init_cookie();
    pub fn __security_check_cookie(_StackCookie: uintptr_t);
    pub fn __report_gsfailure(_StackCookie: uintptr_t);
    pub fn ovr_Initialize(params: *const ovrInitParams) -> ovrResult;
    pub fn ovr_Shutdown();
    pub fn ovr_GetLastErrorInfo(errorInfo: *mut ovrErrorInfo);
    pub fn ovr_GetVersionString() -> *const ::std::os::raw::c_char;
    pub fn ovr_TraceMessage(level: ::std::os::raw::c_int,
                            message: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn ovr_GetHmdDesc(session: ovrSession) -> ovrHmdDesc;
    pub fn ovr_Create(pSession: *mut ovrSession, pLuid: *mut ovrGraphicsLuid)
     -> ovrResult;
    pub fn ovr_Destroy(session: ovrSession);
    pub fn ovr_GetSessionStatus(session: ovrSession,
                                sessionStatus: *mut ovrSessionStatus)
     -> ovrResult;
    pub fn ovr_GetEnabledCaps(session: ovrSession) -> ::std::os::raw::c_uint;
    pub fn ovr_SetEnabledCaps(session: ovrSession,
                              hmdCaps: ::std::os::raw::c_uint);
    pub fn ovr_GetTrackingCaps(session: ovrSession) -> ::std::os::raw::c_uint;
    pub fn ovr_ConfigureTracking(session: ovrSession,
                                 requestedTrackingCaps:
                                     ::std::os::raw::c_uint,
                                 requiredTrackingCaps: ::std::os::raw::c_uint)
     -> ovrResult;
    pub fn ovr_RecenterPose(session: ovrSession);
    pub fn ovr_GetTrackingState(session: ovrSession,
                                absTime: ::std::os::raw::c_double,
                                latencyMarker: ovrBool) -> ovrTrackingState;
    pub fn ovr_GetInputState(session: ovrSession,
                             controllerTypeMask: ::std::os::raw::c_uint,
                             inputState: *mut ovrInputState) -> ovrResult;
    pub fn ovr_SetControllerVibration(session: ovrSession,
                                      controllerTypeMask:
                                          ::std::os::raw::c_uint,
                                      frequency: ::std::os::raw::c_float,
                                      amplitude: ::std::os::raw::c_float)
     -> ovrResult;
    pub fn ovr_DestroySwapTextureSet(session: ovrSession,
                                     textureSet: *mut ovrSwapTextureSet);
    pub fn ovr_DestroyMirrorTexture(session: ovrSession,
                                    mirrorTexture: *mut ovrTexture);
    pub fn ovr_GetFovTextureSize(session: ovrSession, eye: ovrEyeType,
                                 fov: ovrFovPort,
                                 pixelsPerDisplayPixel:
                                     ::std::os::raw::c_float) -> ovrSizei;
    pub fn ovr_GetRenderDesc(session: ovrSession, eyeType: ovrEyeType,
                             fov: ovrFovPort) -> ovrEyeRenderDesc;
    pub fn ovr_SubmitFrame(session: ovrSession,
                           frameIndex: ::std::os::raw::c_longlong,
                           viewScaleDesc: *const ovrViewScaleDesc,
                           layerPtrList: *const *const ovrLayerHeader,
                           layerCount: ::std::os::raw::c_uint) -> ovrResult;
    pub fn ovr_GetPredictedDisplayTime(session: ovrSession,
                                       frameIndex: ::std::os::raw::c_longlong)
     -> ::std::os::raw::c_double;
    pub fn ovr_GetTimeInSeconds() -> ::std::os::raw::c_double;
    pub fn ovr_ResetBackOfHeadTracking(session: ovrSession);
    pub fn ovr_ResetMulticameraTracking(session: ovrSession);
    pub fn ovr_GetBool(session: ovrSession,
                       propertyName: *const ::std::os::raw::c_char,
                       defaultVal: ovrBool) -> ovrBool;
    pub fn ovr_SetBool(session: ovrSession,
                       propertyName: *const ::std::os::raw::c_char,
                       value: ovrBool) -> ovrBool;
    pub fn ovr_GetInt(session: ovrSession,
                      propertyName: *const ::std::os::raw::c_char,
                      defaultVal: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn ovr_SetInt(session: ovrSession,
                      propertyName: *const ::std::os::raw::c_char,
                      value: ::std::os::raw::c_int) -> ovrBool;
    pub fn ovr_GetFloat(session: ovrSession,
                        propertyName: *const ::std::os::raw::c_char,
                        defaultVal: ::std::os::raw::c_float)
     -> ::std::os::raw::c_float;
    pub fn ovr_SetFloat(session: ovrSession,
                        propertyName: *const ::std::os::raw::c_char,
                        value: ::std::os::raw::c_float) -> ovrBool;
    pub fn ovr_GetFloatArray(session: ovrSession,
                             propertyName: *const ::std::os::raw::c_char,
                             values: *mut ::std::os::raw::c_float,
                             valuesCapacity: ::std::os::raw::c_uint)
     -> ::std::os::raw::c_uint;
    pub fn ovr_SetFloatArray(session: ovrSession,
                             propertyName: *const ::std::os::raw::c_char,
                             values: *const ::std::os::raw::c_float,
                             valuesSize: ::std::os::raw::c_uint) -> ovrBool;
    pub fn ovr_GetString(session: ovrSession,
                         propertyName: *const ::std::os::raw::c_char,
                         defaultVal: *const ::std::os::raw::c_char)
     -> *const ::std::os::raw::c_char;
    pub fn ovr_SetString(session: ovrSession,
                         propertyName: *const ::std::os::raw::c_char,
                         value: *const ::std::os::raw::c_char) -> ovrBool;
    pub fn ovr_Detect(timeoutMsec: ::std::os::raw::c_int) -> ovrDetectResult;
    pub fn ovrMatrix4f_Projection(fov: ovrFovPort,
                                  znear: ::std::os::raw::c_float,
                                  zfar: ::std::os::raw::c_float,
                                  projectionModFlags: ::std::os::raw::c_uint)
     -> ovrMatrix4f;
    pub fn ovrTimewarpProjectionDesc_FromProjection(projection: ovrMatrix4f,
                                                    projectionModFlags:
                                                        ::std::os::raw::c_uint)
     -> ovrTimewarpProjectionDesc;
    pub fn ovrMatrix4f_OrthoSubProjection(projection: ovrMatrix4f,
                                          orthoScale: ovrVector2f,
                                          orthoDistance:
                                              ::std::os::raw::c_float,
                                          hmdToEyeViewOffsetX:
                                              ::std::os::raw::c_float)
     -> ovrMatrix4f;
    pub fn ovr_CalcEyePoses(headPose: ovrPosef,
                            hmdToEyeViewOffset: *mut ovrVector3f,
                            outEyePoses: *mut ovrPosef);
    pub fn ovr_GetEyePoses(session: ovrSession,
                           frameIndex: ::std::os::raw::c_longlong,
                           latencyMarker: ovrBool,
                           hmdToEyeViewOffset: *mut ovrVector3f,
                           outEyePoses: *mut ovrPosef,
                           outHmdTrackingState: *mut ovrTrackingState);
}
